### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by konradsienkowski** [bennyxguo/vue3-scroll-spy#1]
Hey, thanks for the great work! Just installed the directive and it works well. 

Though, I think that part of README.md needs correction:
```
// global register at main.js
import { registerScrollSpy } from '@/directives/ScrollSpy'
```
In my case, the code above didn't work. I changed it to:
```
// global register at main.js
import { registerScrollSpy } from 'vue3-scroll-spy';
```

**Comment by bennyxguo** [comment]
Thanks @konradsienkowski I have updated the README.md  👍🏻
